[package]
name = "ivy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.1.8"
serde = "1.0.152"
simple_logger = "4.0.0"
